"""
Django settings for LegalEdge CRM Backend.
"""
import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None


ORIGINAL_ENV_KEYS = set(os.environ.keys())


def load_env_file(path, override=False):
    file_path = Path(path)
    if not file_path.exists():
        return

    for raw_line in file_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip()

        if value and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]

        if key in ORIGINAL_ENV_KEYS:
            continue

        if override or key not in os.environ:
            os.environ[key] = value


BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent

# Allow both monorepo root and backend-local env files.
# Process env vars always win over file values.
env_files_in_precedence_order = [
    PROJECT_ROOT / '.env',
    BASE_DIR / '.env',
    PROJECT_ROOT / '.env.local',
    BASE_DIR / '.env.local',
]
for env_path in env_files_in_precedence_order:
    load_env_file(env_path, override=True)

if load_dotenv:
    for env_path in env_files_in_precedence_order:
        load_dotenv(env_path, override=False)

def env_str(name, default=''):
    value = os.environ.get(name, None)
    if value is None:
        return default
    value = str(value).strip()
    return value if value else default


def env_bool(name, default=False):
    value = env_str(name, str(default))
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    value = env_str(name, default)
    return [item.strip() for item in str(value).split(',') if item.strip()]


def env_int(name, default=0):
    raw = env_str(name, default='')
    if raw == '':
        return default
    try:
        return int(raw)
    except (TypeError, ValueError) as exc:
        raise ImproperlyConfigured(f'{name} must be an integer.') from exc


def env_required(name):
    value = env_str(name, default='')
    if not value:
        raise ImproperlyConfigured(f'{name} environment variable is required.')
    return value


def is_strong_secret_key(secret_value):
    if not secret_value:
        return False
    return (
        len(secret_value) >= 50
        and len(set(secret_value)) >= 5
        and not secret_value.startswith('django-insecure-')
    )


# Security
DEBUG = env_bool('DJANGO_DEBUG', default=False)
SECRET_KEY = os.environ.get('SECRET_KEY', '').strip()
placeholder_secret_keys = {
    'replace-with-a-secret-key',
    'paste-your-new-generated-key-here',
    'django-insecure-change-me',
}
if not SECRET_KEY:
    raise ImproperlyConfigured('SECRET_KEY environment variable is required.')
if SECRET_KEY in placeholder_secret_keys or not is_strong_secret_key(SECRET_KEY):
    raise ImproperlyConfigured('SECRET_KEY is weak. Use a long random value generated by Django.')
if DEBUG and (env_bool('RENDER', default=False) or env_str('RENDER_EXTERNAL_HOSTNAME', default='')):
    raise ImproperlyConfigured('DJANGO_DEBUG=True is not allowed on Render. Set DJANGO_DEBUG=False.')
CRM_ALLOW_ANY = DEBUG and env_bool('CRM_ALLOW_ANY', default=False)

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', default='localhost,127.0.0.1,0.0.0.0,testserver')
ALLOWED_HOSTS = sorted(set(ALLOWED_HOSTS + ['testserver']))
render_hostname = env_str('RENDER_EXTERNAL_HOSTNAME', default='').strip()
if render_hostname:
    ALLOWED_HOSTS = sorted(set(ALLOWED_HOSTS + [render_hostname]))
if env_bool('ALLOW_ONRENDER_HOSTS', default=not DEBUG):
    ALLOWED_HOSTS = sorted(set(ALLOWED_HOSTS + ['.onrender.com']))
if any(host == '*' for host in ALLOWED_HOSTS):
    raise ImproperlyConfigured('ALLOWED_HOSTS cannot contain "*".')
if not DEBUG:
    invalid_local_hosts = {'localhost', '127.0.0.1', '0.0.0.0', 'testserver'}
    production_hosts = [host for host in ALLOWED_HOSTS if host not in invalid_local_hosts]
    if not production_hosts:
        raise ImproperlyConfigured('ALLOWED_HOSTS must include at least one production hostname.')


# Apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'accounts',
    'crm',
]

try:
    import django_filters  # noqa: F401

    INSTALLED_APPS.append('django_filters')
except ImportError:
    pass

try:
    import channels  # noqa: F401

    INSTALLED_APPS.append('channels')
except ImportError:
    pass


# Middleware
MIDDLEWARE = [
    'config.middleware.APIExceptionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
db_conn_max_age = 0 if DEBUG else env_int('DB_CONN_MAX_AGE', default=60)
db_ssl_mode = env_str('DB_SSLMODE', default='prefer' if DEBUG else 'require')
allowed_db_ssl_modes = {'disable', 'allow', 'prefer', 'require', 'verify-ca', 'verify-full'}
if db_ssl_mode not in allowed_db_ssl_modes:
    raise ImproperlyConfigured(
        'DB_SSLMODE must be one of: disable, allow, prefer, require, verify-ca, verify-full.'
    )
if not DEBUG and db_ssl_mode != 'require':
    raise ImproperlyConfigured('In production, DB_SSLMODE must be set to "require".')
DATABASE_URL = env_str('DATABASE_URL', default='').strip()
if not DEBUG and not DATABASE_URL:
    raise ImproperlyConfigured('DATABASE_URL environment variable is required in production.')

if DATABASE_URL:
    parsed_db = dj_database_url.parse(DATABASE_URL, conn_max_age=db_conn_max_age)
    parsed_engine = parsed_db.get('ENGINE')
    if not DEBUG and parsed_engine != 'django.db.backends.postgresql':
        raise ImproperlyConfigured('Production DATABASE_URL must point to PostgreSQL.')
    if parsed_engine == 'django.db.backends.postgresql':
        options = dict(parsed_db.get('OPTIONS') or {})
        options.setdefault('sslmode', db_ssl_mode)
        parsed_db['OPTIONS'] = options
    DATABASES = {'default': parsed_db}
else:
    db_engine = env_str('DB_ENGINE', default='sqlite').strip().lower()
    if not DEBUG and db_engine != 'postgres':
        raise ImproperlyConfigured('Production requires PostgreSQL. Set DATABASE_URL or DB_ENGINE=postgres.')
    if db_engine == 'postgres':
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': env_str('DB_NAME'),
                'USER': env_str('DB_USER'),
                'PASSWORD': env_str('DB_PASSWORD'),
                'HOST': env_str('DB_HOST', default='127.0.0.1'),
                'PORT': env_str('DB_PORT', default='5432'),
                'CONN_MAX_AGE': db_conn_max_age,
                'OPTIONS': {
                    'sslmode': db_ssl_mode,
                },
            }
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# Auth
AUTH_USER_MODEL = 'accounts.CustomUser'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Localization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True


# Static Files
STATIC_URL = '/static/'
STATIC_ROOT = env_str('STATIC_ROOT', default=str(BASE_DIR / 'staticfiles'))
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Frontend
FRONTEND_URL = env_str('FRONTEND_URL', default='http://127.0.0.1:5173').rstrip('/')


# CORS / CSRF
default_cors_origins = [FRONTEND_URL]
if DEBUG:
    default_cors_origins.extend(
        [
            'http://localhost:5173',
            'http://127.0.0.1:5173',
        ]
    )
extra_cors_origins = env_list('CORS_ALLOWED_ORIGINS', default='')

CORS_ALLOWED_ORIGINS = sorted(set(default_cors_origins + extra_cors_origins))
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True
default_csrf_origins = [FRONTEND_URL]
if DEBUG:
    default_csrf_origins.extend(
        [
            'http://localhost:5173',
            'http://127.0.0.1:5173',
        ]
    )
extra_csrf_origins = env_list('CSRF_TRUSTED_ORIGINS', default='')
CSRF_TRUSTED_ORIGINS = sorted(set(default_csrf_origins + extra_csrf_origins))


# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny' if CRM_ALLOW_ANY else 'rest_framework.permissions.IsAuthenticated',
    ),
}


# JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = env_str('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env_str('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# HTTPS (Render)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=not DEBUG)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', default=not DEBUG)
SECURE_HSTS_SECONDS = env_int('SECURE_HSTS_SECONDS', default=(31536000 if not DEBUG else 0))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', default=not DEBUG)
SECURE_CONTENT_TYPE_NOSNIFF = env_bool('SECURE_CONTENT_TYPE_NOSNIFF', default=True)
SECURE_REFERRER_POLICY = env_str('SECURE_REFERRER_POLICY', default='strict-origin-when-cross-origin')
X_FRAME_OPTIONS = env_str('X_FRAME_OPTIONS', default='DENY')

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = max(SECURE_HSTS_SECONDS, 31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
